on: [push, pull_request]

jobs:
  build:
    name: build old-fashion way

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v1
    - run: ./configure
    - run: make
    - run: make test
    - run: make install
